[package]
name = "goxlr-hub"
description = "Open source control app for the TC-Helicon GoXLR (unofficial)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
sys-locale = "0.3"
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-single-instance = "2"
