[package]
name = "goxlr-hub-device"
description = "One device interface for GoXLR Hub, with a real or a virtual device behind it"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
goxlr-hub-protocol = { path = "../protocol" }
goxlr-hub-transport = { path = "../transport" }
thiserror = "2"
